package project5;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.FileNotFoundException;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/*** MorseCodeConverter Student JUnit test cases
 * 
 * @author joeyp
 *
 */
class MorseCodeConverterTest {
	
	private String code1, code2;
	private File file1, file2;
	
	@BeforeEach
	void setUp() throws Exception {
		
		code1 = "- .... .. ... / .. ... / .- / -- --- .-. ... . / -.-. --- -.. . / - . ... -";
		code2 = "- .... .. ... / .. ... / .- -. --- - .... . .-. / -- --- .-. ... . / -.-. --- -.. . / - . ... -";
		
		// Files generated by https://randomwordgenerator.com/paragraph.php
		file1 = new File("src/file1.txt");
		file2 = new File("src/file2.txt");
		
	}

	@AfterEach
	void tearDown() throws Exception {
		
		code1 = code2 = null;
		file1 = file2 = null;
		
	}

	@Test
	void convertToEnglishStringTest() {
		
		assertEquals("this is another morse code test",
				MorseCodeConverter.convertToEnglish(code2));
		
		assertEquals("this is a morse code test",
				MorseCodeConverter.convertToEnglish(code1));
		
	}
	
	@Test
	void convertToEnglishFileTest() {
		
		try {
			
			assertEquals("there was only one way to do things in the statton house that one way was to do exactly what the father charlie demanded he made the decisions and everyone else followed without question that was until today",
					MorseCodeConverter.convertToEnglish(file1));
			
			assertEquals("he heard the song coming from a distance lightly floating over the air to his ears although it was soft and calming he was wary it seemed a little too soft and a little too calming for everything that was going on he wanted it to be nothing more than beautiful music coming from the innocent and pure joy of singing but in the back of his mind he knew it was likely some type of trap", 
					MorseCodeConverter.convertToEnglish(file2));
		
		
		
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		
	}

}
